/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 121
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 64
#define ALIAS_COUNT 0
#define TOKEN_COUNT 36
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_module = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_alias = 4,
  anon_sym_COLON_EQ = 5,
  anon_sym_SEMI = 6,
  anon_sym_scalar = 7,
  anon_sym_type = 8,
  anon_sym_extending = 9,
  anon_sym_COLON = 10,
  anon_sym_overloaded = 11,
  anon_sym_required = 12,
  anon_sym_multi = 13,
  anon_sym_annotation = 14,
  anon_sym_COLON_COLON = 15,
  anon_sym_trigger = 16,
  anon_sym_after = 17,
  anon_sym_before = 18,
  anon_sym_for = 19,
  anon_sym_each = 20,
  anon_sym_when = 21,
  anon_sym_do = 22,
  anon_sym_LPAREN = 23,
  anon_sym_RPAREN = 24,
  anon_sym_LT = 25,
  anon_sym_COMMA = 26,
  anon_sym_GT = 27,
  sym_number = 28,
  sym_string = 29,
  sym_identifier = 30,
  anon_sym_SLASH_SLASH = 31,
  aux_sym_comment_token1 = 32,
  anon_sym_SLASH_STAR = 33,
  aux_sym_multi_line_comment_token1 = 34,
  anon_sym_SLASH = 35,
  sym_source_file = 36,
  sym__statement = 37,
  sym_module_def = 38,
  sym_alias_stmt = 39,
  sym_scalar_def = 40,
  sym_type_def = 41,
  sym__type_body = 42,
  sym_field = 43,
  sym_overloaded_field = 44,
  sym_field_attributes = 45,
  sym_annotation = 46,
  sym_qualified_identifier = 47,
  sym_trigger = 48,
  sym_trigger_modifier = 49,
  sym_trigger_for_each = 50,
  sym_trigger_when = 51,
  sym_trigger_do = 52,
  sym_type_name = 53,
  sym_expression = 54,
  sym_comment = 55,
  sym_multi_line_comment = 56,
  sym_semicolon = 57,
  aux_sym_source_file_repeat1 = 58,
  aux_sym_type_def_repeat1 = 59,
  aux_sym_field_attributes_repeat1 = 60,
  aux_sym_qualified_identifier_repeat1 = 61,
  aux_sym_trigger_do_repeat1 = 62,
  aux_sym_type_name_repeat1 = 63,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_module] = "module",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_alias] = "alias",
  [anon_sym_COLON_EQ] = ":=",
  [anon_sym_SEMI] = ";",
  [anon_sym_scalar] = "scalar",
  [anon_sym_type] = "type",
  [anon_sym_extending] = "extending",
  [anon_sym_COLON] = ":",
  [anon_sym_overloaded] = "overloaded",
  [anon_sym_required] = "required",
  [anon_sym_multi] = "multi",
  [anon_sym_annotation] = "annotation",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_trigger] = "trigger",
  [anon_sym_after] = "after",
  [anon_sym_before] = "before",
  [anon_sym_for] = "for",
  [anon_sym_each] = "each",
  [anon_sym_when] = "when",
  [anon_sym_do] = "do",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LT] = "<",
  [anon_sym_COMMA] = ",",
  [anon_sym_GT] = ">",
  [sym_number] = "number",
  [sym_string] = "string",
  [sym_identifier] = "identifier",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_SLASH_STAR] = "/*",
  [aux_sym_multi_line_comment_token1] = "multi_line_comment_token1",
  [anon_sym_SLASH] = "/",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_module_def] = "module_def",
  [sym_alias_stmt] = "alias_stmt",
  [sym_scalar_def] = "scalar_def",
  [sym_type_def] = "type_def",
  [sym__type_body] = "_type_body",
  [sym_field] = "field",
  [sym_overloaded_field] = "overloaded_field",
  [sym_field_attributes] = "field_attributes",
  [sym_annotation] = "annotation",
  [sym_qualified_identifier] = "qualified_identifier",
  [sym_trigger] = "trigger",
  [sym_trigger_modifier] = "trigger_modifier",
  [sym_trigger_for_each] = "trigger_for_each",
  [sym_trigger_when] = "trigger_when",
  [sym_trigger_do] = "trigger_do",
  [sym_type_name] = "type_name",
  [sym_expression] = "expression",
  [sym_comment] = "comment",
  [sym_multi_line_comment] = "multi_line_comment",
  [sym_semicolon] = "semicolon",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_type_def_repeat1] = "type_def_repeat1",
  [aux_sym_field_attributes_repeat1] = "field_attributes_repeat1",
  [aux_sym_qualified_identifier_repeat1] = "qualified_identifier_repeat1",
  [aux_sym_trigger_do_repeat1] = "trigger_do_repeat1",
  [aux_sym_type_name_repeat1] = "type_name_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_module] = anon_sym_module,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_alias] = anon_sym_alias,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_scalar] = anon_sym_scalar,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_extending] = anon_sym_extending,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_overloaded] = anon_sym_overloaded,
  [anon_sym_required] = anon_sym_required,
  [anon_sym_multi] = anon_sym_multi,
  [anon_sym_annotation] = anon_sym_annotation,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_trigger] = anon_sym_trigger,
  [anon_sym_after] = anon_sym_after,
  [anon_sym_before] = anon_sym_before,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_each] = anon_sym_each,
  [anon_sym_when] = anon_sym_when,
  [anon_sym_do] = anon_sym_do,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_GT] = anon_sym_GT,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [sym_identifier] = sym_identifier,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [aux_sym_multi_line_comment_token1] = aux_sym_multi_line_comment_token1,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_module_def] = sym_module_def,
  [sym_alias_stmt] = sym_alias_stmt,
  [sym_scalar_def] = sym_scalar_def,
  [sym_type_def] = sym_type_def,
  [sym__type_body] = sym__type_body,
  [sym_field] = sym_field,
  [sym_overloaded_field] = sym_overloaded_field,
  [sym_field_attributes] = sym_field_attributes,
  [sym_annotation] = sym_annotation,
  [sym_qualified_identifier] = sym_qualified_identifier,
  [sym_trigger] = sym_trigger,
  [sym_trigger_modifier] = sym_trigger_modifier,
  [sym_trigger_for_each] = sym_trigger_for_each,
  [sym_trigger_when] = sym_trigger_when,
  [sym_trigger_do] = sym_trigger_do,
  [sym_type_name] = sym_type_name,
  [sym_expression] = sym_expression,
  [sym_comment] = sym_comment,
  [sym_multi_line_comment] = sym_multi_line_comment,
  [sym_semicolon] = sym_semicolon,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_type_def_repeat1] = aux_sym_type_def_repeat1,
  [aux_sym_field_attributes_repeat1] = aux_sym_field_attributes_repeat1,
  [aux_sym_qualified_identifier_repeat1] = aux_sym_qualified_identifier_repeat1,
  [aux_sym_trigger_do_repeat1] = aux_sym_trigger_do_repeat1,
  [aux_sym_type_name_repeat1] = aux_sym_type_name_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_module] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_alias] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_scalar] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extending] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_overloaded] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_required] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_multi] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_annotation] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_trigger] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_after] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_before] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_each] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_when] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_do] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_multi_line_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_module_def] = {
    .visible = true,
    .named = true,
  },
  [sym_alias_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_scalar_def] = {
    .visible = true,
    .named = true,
  },
  [sym_type_def] = {
    .visible = true,
    .named = true,
  },
  [sym__type_body] = {
    .visible = false,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_overloaded_field] = {
    .visible = true,
    .named = true,
  },
  [sym_field_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_annotation] = {
    .visible = true,
    .named = true,
  },
  [sym_qualified_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_trigger] = {
    .visible = true,
    .named = true,
  },
  [sym_trigger_modifier] = {
    .visible = true,
    .named = true,
  },
  [sym_trigger_for_each] = {
    .visible = true,
    .named = true,
  },
  [sym_trigger_when] = {
    .visible = true,
    .named = true,
  },
  [sym_trigger_do] = {
    .visible = true,
    .named = true,
  },
  [sym_type_name] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_multi_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_semicolon] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_def_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_field_attributes_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_qualified_identifier_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_trigger_do_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_name_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 13,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 12,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 52,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 114,
  [118] = 97,
  [119] = 109,
  [120] = 120,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(86);
      ADVANCE_MAP(
        '"', 2,
        '(', 113,
        ')', 114,
        ',', 116,
        '/', 152,
        ':', 97,
        ';', 92,
        '<', 115,
        '>', 117,
        'a', 33,
        'b', 21,
        'd', 56,
        'e', 9,
        'f', 57,
        'm', 58,
        'o', 81,
        'r', 22,
        's', 14,
        't', 69,
        'w', 39,
        '{', 88,
        '}', 89,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(118);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == ')') ADVANCE(114);
      if (lookahead == '/') ADVANCE(151);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(118);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(145);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(120);
      if (lookahead == '\\') ADVANCE(84);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(149);
      if (lookahead == '/') ADVANCE(146);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(150);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(150);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == ':') ADVANCE(7);
      if (lookahead == 'a') ADVANCE(135);
      if (lookahead == 'o') ADVANCE(144);
      if (lookahead == 't') ADVANCE(139);
      if (lookahead == '}') ADVANCE(89);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(145);
      END_STATE();
    case 7:
      if (lookahead == ':') ADVANCE(104);
      if (lookahead == '=') ADVANCE(91);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(73);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(15);
      if (lookahead == 'x') ADVANCE(77);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(48);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(20);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(67);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(78);
      END_STATE();
    case 14:
      if (lookahead == 'c') ADVANCE(10);
      END_STATE();
    case 15:
      if (lookahead == 'c') ADVANCE(38);
      END_STATE();
    case 16:
      if (lookahead == 'd') ADVANCE(79);
      END_STATE();
    case 17:
      if (lookahead == 'd') ADVANCE(100);
      END_STATE();
    case 18:
      if (lookahead == 'd') ADVANCE(98);
      END_STATE();
    case 19:
      if (lookahead == 'd') ADVANCE(43);
      END_STATE();
    case 20:
      if (lookahead == 'd') ADVANCE(31);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(64);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(94);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(108);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(87);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(51);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(70);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(53);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(66);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 32:
      if (lookahead == 'e') ADVANCE(68);
      END_STATE();
    case 33:
      if (lookahead == 'f') ADVANCE(76);
      if (lookahead == 'l') ADVANCE(42);
      if (lookahead == 'n') ADVANCE(54);
      END_STATE();
    case 34:
      if (lookahead == 'f') ADVANCE(60);
      END_STATE();
    case 35:
      if (lookahead == 'g') ADVANCE(95);
      END_STATE();
    case 36:
      if (lookahead == 'g') ADVANCE(37);
      END_STATE();
    case 37:
      if (lookahead == 'g') ADVANCE(32);
      END_STATE();
    case 38:
      if (lookahead == 'h') ADVANCE(110);
      END_STATE();
    case 39:
      if (lookahead == 'h') ADVANCE(26);
      END_STATE();
    case 40:
      if (lookahead == 'i') ADVANCE(36);
      END_STATE();
    case 41:
      if (lookahead == 'i') ADVANCE(101);
      END_STATE();
    case 42:
      if (lookahead == 'i') ADVANCE(8);
      END_STATE();
    case 43:
      if (lookahead == 'i') ADVANCE(55);
      END_STATE();
    case 44:
      if (lookahead == 'i') ADVANCE(61);
      END_STATE();
    case 45:
      if (lookahead == 'i') ADVANCE(72);
      END_STATE();
    case 46:
      if (lookahead == 'l') ADVANCE(42);
      END_STATE();
    case 47:
      if (lookahead == 'l') ADVANCE(74);
      END_STATE();
    case 48:
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 49:
      if (lookahead == 'l') ADVANCE(62);
      END_STATE();
    case 50:
      if (lookahead == 'l') ADVANCE(25);
      END_STATE();
    case 51:
      if (lookahead == 'n') ADVANCE(111);
      END_STATE();
    case 52:
      if (lookahead == 'n') ADVANCE(102);
      END_STATE();
    case 53:
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 54:
      if (lookahead == 'n') ADVANCE(59);
      END_STATE();
    case 55:
      if (lookahead == 'n') ADVANCE(35);
      END_STATE();
    case 56:
      if (lookahead == 'o') ADVANCE(112);
      END_STATE();
    case 57:
      if (lookahead == 'o') ADVANCE(65);
      END_STATE();
    case 58:
      if (lookahead == 'o') ADVANCE(16);
      if (lookahead == 'u') ADVANCE(47);
      END_STATE();
    case 59:
      if (lookahead == 'o') ADVANCE(75);
      END_STATE();
    case 60:
      if (lookahead == 'o') ADVANCE(71);
      END_STATE();
    case 61:
      if (lookahead == 'o') ADVANCE(52);
      END_STATE();
    case 62:
      if (lookahead == 'o') ADVANCE(11);
      END_STATE();
    case 63:
      if (lookahead == 'p') ADVANCE(23);
      END_STATE();
    case 64:
      if (lookahead == 'q') ADVANCE(80);
      END_STATE();
    case 65:
      if (lookahead == 'r') ADVANCE(109);
      END_STATE();
    case 66:
      if (lookahead == 'r') ADVANCE(107);
      END_STATE();
    case 67:
      if (lookahead == 'r') ADVANCE(93);
      END_STATE();
    case 68:
      if (lookahead == 'r') ADVANCE(105);
      END_STATE();
    case 69:
      if (lookahead == 'r') ADVANCE(40);
      if (lookahead == 'y') ADVANCE(63);
      END_STATE();
    case 70:
      if (lookahead == 'r') ADVANCE(49);
      END_STATE();
    case 71:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 72:
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 73:
      if (lookahead == 's') ADVANCE(90);
      END_STATE();
    case 74:
      if (lookahead == 't') ADVANCE(41);
      END_STATE();
    case 75:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 76:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 77:
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 78:
      if (lookahead == 't') ADVANCE(44);
      END_STATE();
    case 79:
      if (lookahead == 'u') ADVANCE(50);
      END_STATE();
    case 80:
      if (lookahead == 'u') ADVANCE(45);
      END_STATE();
    case 81:
      if (lookahead == 'v') ADVANCE(27);
      END_STATE();
    case 82:
      if (lookahead == 'y') ADVANCE(63);
      END_STATE();
    case 83:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(119);
      END_STATE();
    case 84:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 85:
      if (eof) ADVANCE(86);
      ADVANCE_MAP(
        '/', 3,
        ':', 96,
        ';', 92,
        '<', 115,
        'a', 46,
        'm', 58,
        'r', 22,
        's', 14,
        't', 82,
        '{', 88,
        '}', 89,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(85);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_module);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_alias);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_scalar);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_extending);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(104);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(104);
      if (lookahead == '=') ADVANCE(91);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_overloaded);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_overloaded);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(145);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_required);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_multi);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_annotation);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_annotation);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(145);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_trigger);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_trigger);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(145);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_after);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_before);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_each);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_when);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_do);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(83);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(118);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(119);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(124);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(145);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(143);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(145);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(99);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(145);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(126);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(145);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(140);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(145);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(123);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(145);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(141);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(145);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(129);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(145);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(127);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(145);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(128);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(145);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(138);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(145);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(137);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(145);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(136);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(145);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(145);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(133);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(145);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(142);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(145);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(121);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(145);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(134);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(145);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(130);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(145);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(132);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(145);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(106);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(145);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(122);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(145);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(131);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(145);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'v') ADVANCE(125);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(145);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(145);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(147);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(148);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(148);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(aux_sym_multi_line_comment_token1);
      if (lookahead == '*') ADVANCE(150);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(5);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(149);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 85},
  [2] = {.lex_state = 85},
  [3] = {.lex_state = 85},
  [4] = {.lex_state = 85},
  [5] = {.lex_state = 85},
  [6] = {.lex_state = 6},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 85},
  [13] = {.lex_state = 85},
  [14] = {.lex_state = 85},
  [15] = {.lex_state = 85},
  [16] = {.lex_state = 85},
  [17] = {.lex_state = 85},
  [18] = {.lex_state = 85},
  [19] = {.lex_state = 85},
  [20] = {.lex_state = 85},
  [21] = {.lex_state = 85},
  [22] = {.lex_state = 85},
  [23] = {.lex_state = 85},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 6},
  [26] = {.lex_state = 6},
  [27] = {.lex_state = 6},
  [28] = {.lex_state = 6},
  [29] = {.lex_state = 85},
  [30] = {.lex_state = 6},
  [31] = {.lex_state = 6},
  [32] = {.lex_state = 6},
  [33] = {.lex_state = 6},
  [34] = {.lex_state = 6},
  [35] = {.lex_state = 6},
  [36] = {.lex_state = 6},
  [37] = {.lex_state = 6},
  [38] = {.lex_state = 6},
  [39] = {.lex_state = 85},
  [40] = {.lex_state = 85},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 85},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 85},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 85},
  [50] = {.lex_state = 85},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 6},
  [59] = {.lex_state = 6},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 6},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 6},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 85},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 1},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 1},
  [94] = {.lex_state = 1},
  [95] = {.lex_state = 1},
  [96] = {.lex_state = 1},
  [97] = {.lex_state = 1},
  [98] = {.lex_state = 1},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 85},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 6},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 6},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 4},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 1},
  [112] = {.lex_state = 1},
  [113] = {.lex_state = 1},
  [114] = {.lex_state = 147},
  [115] = {.lex_state = 1},
  [116] = {.lex_state = 1},
  [117] = {.lex_state = 147},
  [118] = {.lex_state = 1},
  [119] = {.lex_state = 4},
  [120] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_module] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_alias] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_scalar] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_extending] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_overloaded] = ACTIONS(1),
    [anon_sym_required] = ACTIONS(1),
    [anon_sym_multi] = ACTIONS(1),
    [anon_sym_annotation] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_trigger] = ACTIONS(1),
    [anon_sym_after] = ACTIONS(1),
    [anon_sym_before] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_each] = ACTIONS(1),
    [anon_sym_when] = ACTIONS(1),
    [anon_sym_do] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_SLASH_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(104),
    [sym__statement] = STATE(3),
    [sym_module_def] = STATE(3),
    [sym_alias_stmt] = STATE(3),
    [sym_scalar_def] = STATE(3),
    [sym_type_def] = STATE(3),
    [sym_comment] = STATE(3),
    [sym_multi_line_comment] = STATE(3),
    [sym_semicolon] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_module] = ACTIONS(5),
    [anon_sym_alias] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_scalar] = ACTIONS(11),
    [anon_sym_type] = ACTIONS(13),
    [anon_sym_SLASH_SLASH] = ACTIONS(15),
    [anon_sym_SLASH_STAR] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(21), 1,
      anon_sym_module,
    ACTIONS(24), 1,
      anon_sym_alias,
    ACTIONS(27), 1,
      anon_sym_SEMI,
    ACTIONS(30), 1,
      anon_sym_scalar,
    ACTIONS(33), 1,
      anon_sym_type,
    ACTIONS(36), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(39), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(19), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(2), 9,
      sym__statement,
      sym_module_def,
      sym_alias_stmt,
      sym_scalar_def,
      sym_type_def,
      sym_comment,
      sym_multi_line_comment,
      sym_semicolon,
      aux_sym_source_file_repeat1,
  [37] = 9,
    ACTIONS(5), 1,
      anon_sym_module,
    ACTIONS(7), 1,
      anon_sym_alias,
    ACTIONS(9), 1,
      anon_sym_SEMI,
    ACTIONS(11), 1,
      anon_sym_scalar,
    ACTIONS(13), 1,
      anon_sym_type,
    ACTIONS(15), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(17), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(42), 1,
      ts_builtin_sym_end,
    STATE(2), 9,
      sym__statement,
      sym_module_def,
      sym_alias_stmt,
      sym_scalar_def,
      sym_type_def,
      sym_comment,
      sym_multi_line_comment,
      sym_semicolon,
      aux_sym_source_file_repeat1,
  [73] = 9,
    ACTIONS(5), 1,
      anon_sym_module,
    ACTIONS(7), 1,
      anon_sym_alias,
    ACTIONS(9), 1,
      anon_sym_SEMI,
    ACTIONS(11), 1,
      anon_sym_scalar,
    ACTIONS(13), 1,
      anon_sym_type,
    ACTIONS(15), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(17), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(44), 1,
      anon_sym_RBRACE,
    STATE(5), 9,
      sym__statement,
      sym_module_def,
      sym_alias_stmt,
      sym_scalar_def,
      sym_type_def,
      sym_comment,
      sym_multi_line_comment,
      sym_semicolon,
      aux_sym_source_file_repeat1,
  [109] = 9,
    ACTIONS(5), 1,
      anon_sym_module,
    ACTIONS(7), 1,
      anon_sym_alias,
    ACTIONS(9), 1,
      anon_sym_SEMI,
    ACTIONS(11), 1,
      anon_sym_scalar,
    ACTIONS(13), 1,
      anon_sym_type,
    ACTIONS(15), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(17), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(46), 1,
      anon_sym_RBRACE,
    STATE(2), 9,
      sym__statement,
      sym_module_def,
      sym_alias_stmt,
      sym_scalar_def,
      sym_type_def,
      sym_comment,
      sym_multi_line_comment,
      sym_semicolon,
      aux_sym_source_file_repeat1,
  [145] = 8,
    ACTIONS(48), 1,
      anon_sym_RBRACE,
    ACTIONS(50), 1,
      anon_sym_overloaded,
    ACTIONS(52), 1,
      anon_sym_annotation,
    ACTIONS(54), 1,
      anon_sym_trigger,
    ACTIONS(56), 1,
      sym_identifier,
    ACTIONS(58), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(60), 1,
      anon_sym_SLASH_STAR,
    STATE(7), 8,
      sym__type_body,
      sym_field,
      sym_overloaded_field,
      sym_annotation,
      sym_trigger,
      sym_comment,
      sym_multi_line_comment,
      aux_sym_type_def_repeat1,
  [177] = 8,
    ACTIONS(50), 1,
      anon_sym_overloaded,
    ACTIONS(52), 1,
      anon_sym_annotation,
    ACTIONS(54), 1,
      anon_sym_trigger,
    ACTIONS(56), 1,
      sym_identifier,
    ACTIONS(58), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(60), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(62), 1,
      anon_sym_RBRACE,
    STATE(9), 8,
      sym__type_body,
      sym_field,
      sym_overloaded_field,
      sym_annotation,
      sym_trigger,
      sym_comment,
      sym_multi_line_comment,
      aux_sym_type_def_repeat1,
  [209] = 8,
    ACTIONS(50), 1,
      anon_sym_overloaded,
    ACTIONS(52), 1,
      anon_sym_annotation,
    ACTIONS(54), 1,
      anon_sym_trigger,
    ACTIONS(56), 1,
      sym_identifier,
    ACTIONS(58), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(60), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(64), 1,
      anon_sym_RBRACE,
    STATE(10), 8,
      sym__type_body,
      sym_field,
      sym_overloaded_field,
      sym_annotation,
      sym_trigger,
      sym_comment,
      sym_multi_line_comment,
      aux_sym_type_def_repeat1,
  [241] = 8,
    ACTIONS(66), 1,
      anon_sym_RBRACE,
    ACTIONS(68), 1,
      anon_sym_overloaded,
    ACTIONS(71), 1,
      anon_sym_annotation,
    ACTIONS(74), 1,
      anon_sym_trigger,
    ACTIONS(77), 1,
      sym_identifier,
    ACTIONS(80), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(83), 1,
      anon_sym_SLASH_STAR,
    STATE(9), 8,
      sym__type_body,
      sym_field,
      sym_overloaded_field,
      sym_annotation,
      sym_trigger,
      sym_comment,
      sym_multi_line_comment,
      aux_sym_type_def_repeat1,
  [273] = 8,
    ACTIONS(50), 1,
      anon_sym_overloaded,
    ACTIONS(52), 1,
      anon_sym_annotation,
    ACTIONS(54), 1,
      anon_sym_trigger,
    ACTIONS(56), 1,
      sym_identifier,
    ACTIONS(58), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(60), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(86), 1,
      anon_sym_RBRACE,
    STATE(9), 8,
      sym__type_body,
      sym_field,
      sym_overloaded_field,
      sym_annotation,
      sym_trigger,
      sym_comment,
      sym_multi_line_comment,
      aux_sym_type_def_repeat1,
  [305] = 9,
    ACTIONS(88), 1,
      anon_sym_SEMI,
    ACTIONS(92), 1,
      anon_sym_for,
    ACTIONS(94), 1,
      anon_sym_when,
    ACTIONS(96), 1,
      anon_sym_do,
    STATE(24), 1,
      sym_trigger_modifier,
    STATE(47), 1,
      sym_trigger_for_each,
    STATE(57), 1,
      sym_trigger_when,
    STATE(120), 1,
      sym_trigger_do,
    ACTIONS(90), 2,
      anon_sym_after,
      anon_sym_before,
  [334] = 1,
    ACTIONS(98), 9,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_alias,
      anon_sym_SEMI,
      anon_sym_scalar,
      anon_sym_type,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
  [346] = 1,
    ACTIONS(100), 9,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_alias,
      anon_sym_SEMI,
      anon_sym_scalar,
      anon_sym_type,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
  [358] = 1,
    ACTIONS(102), 9,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_alias,
      anon_sym_SEMI,
      anon_sym_scalar,
      anon_sym_type,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
  [370] = 1,
    ACTIONS(104), 9,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_alias,
      anon_sym_SEMI,
      anon_sym_scalar,
      anon_sym_type,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
  [382] = 1,
    ACTIONS(106), 9,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_alias,
      anon_sym_SEMI,
      anon_sym_scalar,
      anon_sym_type,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
  [394] = 1,
    ACTIONS(108), 9,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_alias,
      anon_sym_SEMI,
      anon_sym_scalar,
      anon_sym_type,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
  [406] = 1,
    ACTIONS(110), 9,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_alias,
      anon_sym_SEMI,
      anon_sym_scalar,
      anon_sym_type,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
  [418] = 1,
    ACTIONS(112), 9,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_alias,
      anon_sym_SEMI,
      anon_sym_scalar,
      anon_sym_type,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
  [430] = 1,
    ACTIONS(114), 9,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_alias,
      anon_sym_SEMI,
      anon_sym_scalar,
      anon_sym_type,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
  [442] = 1,
    ACTIONS(116), 9,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_alias,
      anon_sym_SEMI,
      anon_sym_scalar,
      anon_sym_type,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
  [454] = 1,
    ACTIONS(118), 9,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_alias,
      anon_sym_SEMI,
      anon_sym_scalar,
      anon_sym_type,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
  [466] = 1,
    ACTIONS(120), 9,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_alias,
      anon_sym_SEMI,
      anon_sym_scalar,
      anon_sym_type,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
  [478] = 7,
    ACTIONS(92), 1,
      anon_sym_for,
    ACTIONS(94), 1,
      anon_sym_when,
    ACTIONS(96), 1,
      anon_sym_do,
    ACTIONS(122), 1,
      anon_sym_SEMI,
    STATE(44), 1,
      sym_trigger_for_each,
    STATE(61), 1,
      sym_trigger_when,
    STATE(84), 1,
      sym_trigger_do,
  [500] = 2,
    ACTIONS(124), 3,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
    ACTIONS(126), 4,
      anon_sym_overloaded,
      anon_sym_annotation,
      anon_sym_trigger,
      sym_identifier,
  [512] = 2,
    ACTIONS(128), 3,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
    ACTIONS(130), 4,
      anon_sym_overloaded,
      anon_sym_annotation,
      anon_sym_trigger,
      sym_identifier,
  [524] = 2,
    ACTIONS(132), 3,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
    ACTIONS(134), 4,
      anon_sym_overloaded,
      anon_sym_annotation,
      anon_sym_trigger,
      sym_identifier,
  [536] = 2,
    ACTIONS(136), 3,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
    ACTIONS(138), 4,
      anon_sym_overloaded,
      anon_sym_annotation,
      anon_sym_trigger,
      sym_identifier,
  [548] = 4,
    ACTIONS(142), 1,
      anon_sym_COLON,
    ACTIONS(144), 1,
      anon_sym_COLON_COLON,
    ACTIONS(146), 1,
      anon_sym_LT,
    ACTIONS(140), 4,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_required,
      anon_sym_multi,
  [564] = 2,
    ACTIONS(148), 3,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
    ACTIONS(150), 4,
      anon_sym_overloaded,
      anon_sym_annotation,
      anon_sym_trigger,
      sym_identifier,
  [576] = 2,
    ACTIONS(100), 3,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
    ACTIONS(152), 4,
      anon_sym_overloaded,
      anon_sym_annotation,
      anon_sym_trigger,
      sym_identifier,
  [588] = 2,
    ACTIONS(154), 3,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
    ACTIONS(156), 4,
      anon_sym_overloaded,
      anon_sym_annotation,
      anon_sym_trigger,
      sym_identifier,
  [600] = 2,
    ACTIONS(158), 3,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
    ACTIONS(160), 4,
      anon_sym_overloaded,
      anon_sym_annotation,
      anon_sym_trigger,
      sym_identifier,
  [612] = 2,
    ACTIONS(162), 3,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
    ACTIONS(164), 4,
      anon_sym_overloaded,
      anon_sym_annotation,
      anon_sym_trigger,
      sym_identifier,
  [624] = 2,
    ACTIONS(166), 3,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
    ACTIONS(168), 4,
      anon_sym_overloaded,
      anon_sym_annotation,
      anon_sym_trigger,
      sym_identifier,
  [636] = 2,
    ACTIONS(98), 3,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
    ACTIONS(170), 4,
      anon_sym_overloaded,
      anon_sym_annotation,
      anon_sym_trigger,
      sym_identifier,
  [648] = 2,
    ACTIONS(172), 3,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
    ACTIONS(174), 4,
      anon_sym_overloaded,
      anon_sym_annotation,
      anon_sym_trigger,
      sym_identifier,
  [660] = 2,
    ACTIONS(176), 3,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
    ACTIONS(178), 4,
      anon_sym_overloaded,
      anon_sym_annotation,
      anon_sym_trigger,
      sym_identifier,
  [672] = 2,
    ACTIONS(182), 1,
      anon_sym_LT,
    ACTIONS(180), 5,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_required,
      anon_sym_multi,
  [683] = 5,
    ACTIONS(184), 1,
      anon_sym_SEMI,
    ACTIONS(186), 1,
      anon_sym_COLON,
    STATE(55), 1,
      aux_sym_field_attributes_repeat1,
    STATE(87), 1,
      sym_field_attributes,
    ACTIONS(188), 2,
      anon_sym_required,
      anon_sym_multi,
  [700] = 3,
    ACTIONS(190), 1,
      anon_sym_RPAREN,
    STATE(41), 2,
      sym_expression,
      aux_sym_trigger_do_repeat1,
    ACTIONS(192), 3,
      sym_number,
      sym_string,
      sym_identifier,
  [713] = 3,
    ACTIONS(195), 1,
      anon_sym_RPAREN,
    STATE(41), 2,
      sym_expression,
      aux_sym_trigger_do_repeat1,
    ACTIONS(197), 3,
      sym_number,
      sym_string,
      sym_identifier,
  [726] = 1,
    ACTIONS(199), 5,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_required,
      anon_sym_multi,
  [734] = 5,
    ACTIONS(94), 1,
      anon_sym_when,
    ACTIONS(96), 1,
      anon_sym_do,
    ACTIONS(201), 1,
      anon_sym_SEMI,
    STATE(65), 1,
      sym_trigger_when,
    STATE(99), 1,
      sym_trigger_do,
  [750] = 1,
    ACTIONS(203), 5,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_required,
      anon_sym_multi,
  [758] = 2,
    STATE(42), 2,
      sym_expression,
      aux_sym_trigger_do_repeat1,
    ACTIONS(197), 3,
      sym_number,
      sym_string,
      sym_identifier,
  [768] = 5,
    ACTIONS(94), 1,
      anon_sym_when,
    ACTIONS(96), 1,
      anon_sym_do,
    ACTIONS(122), 1,
      anon_sym_SEMI,
    STATE(61), 1,
      sym_trigger_when,
    STATE(84), 1,
      sym_trigger_do,
  [784] = 4,
    ACTIONS(205), 1,
      anon_sym_SEMI,
    STATE(55), 1,
      aux_sym_field_attributes_repeat1,
    STATE(110), 1,
      sym_field_attributes,
    ACTIONS(188), 2,
      anon_sym_required,
      anon_sym_multi,
  [798] = 1,
    ACTIONS(207), 5,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_required,
      anon_sym_multi,
  [806] = 1,
    ACTIONS(209), 5,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_required,
      anon_sym_multi,
  [814] = 2,
    STATE(73), 1,
      sym_expression,
    ACTIONS(211), 3,
      sym_number,
      sym_string,
      sym_identifier,
  [823] = 1,
    ACTIONS(213), 4,
      anon_sym_RPAREN,
      sym_number,
      sym_string,
      sym_identifier,
  [830] = 1,
    ACTIONS(215), 4,
      anon_sym_SEMI,
      anon_sym_for,
      anon_sym_when,
      anon_sym_do,
  [837] = 2,
    STATE(89), 1,
      sym_expression,
    ACTIONS(211), 3,
      sym_number,
      sym_string,
      sym_identifier,
  [846] = 3,
    ACTIONS(217), 1,
      anon_sym_SEMI,
    STATE(56), 1,
      aux_sym_field_attributes_repeat1,
    ACTIONS(219), 2,
      anon_sym_required,
      anon_sym_multi,
  [857] = 3,
    ACTIONS(221), 1,
      anon_sym_SEMI,
    STATE(56), 1,
      aux_sym_field_attributes_repeat1,
    ACTIONS(223), 2,
      anon_sym_required,
      anon_sym_multi,
  [868] = 3,
    ACTIONS(96), 1,
      anon_sym_do,
    ACTIONS(122), 1,
      anon_sym_SEMI,
    STATE(84), 1,
      sym_trigger_do,
  [878] = 3,
    ACTIONS(226), 1,
      anon_sym_COLON_EQ,
    ACTIONS(228), 1,
      anon_sym_COLON_COLON,
    STATE(58), 1,
      aux_sym_qualified_identifier_repeat1,
  [888] = 3,
    ACTIONS(231), 1,
      anon_sym_COLON_EQ,
    ACTIONS(233), 1,
      anon_sym_COLON_COLON,
    STATE(58), 1,
      aux_sym_qualified_identifier_repeat1,
  [898] = 3,
    ACTIONS(235), 1,
      anon_sym_COMMA,
    ACTIONS(237), 1,
      anon_sym_GT,
    STATE(64), 1,
      aux_sym_type_name_repeat1,
  [908] = 3,
    ACTIONS(96), 1,
      anon_sym_do,
    ACTIONS(201), 1,
      anon_sym_SEMI,
    STATE(99), 1,
      sym_trigger_do,
  [918] = 1,
    ACTIONS(239), 3,
      anon_sym_SEMI,
      anon_sym_when,
      anon_sym_do,
  [924] = 3,
    ACTIONS(235), 1,
      anon_sym_COMMA,
    ACTIONS(241), 1,
      anon_sym_GT,
    STATE(67), 1,
      aux_sym_type_name_repeat1,
  [934] = 3,
    ACTIONS(243), 1,
      anon_sym_COMMA,
    ACTIONS(246), 1,
      anon_sym_GT,
    STATE(64), 1,
      aux_sym_type_name_repeat1,
  [944] = 3,
    ACTIONS(96), 1,
      anon_sym_do,
    ACTIONS(248), 1,
      anon_sym_SEMI,
    STATE(108), 1,
      sym_trigger_do,
  [954] = 3,
    ACTIONS(233), 1,
      anon_sym_COLON_COLON,
    ACTIONS(250), 1,
      anon_sym_COLON_EQ,
    STATE(59), 1,
      aux_sym_qualified_identifier_repeat1,
  [964] = 3,
    ACTIONS(235), 1,
      anon_sym_COMMA,
    ACTIONS(252), 1,
      anon_sym_GT,
    STATE(64), 1,
      aux_sym_type_name_repeat1,
  [974] = 3,
    ACTIONS(235), 1,
      anon_sym_COMMA,
    ACTIONS(254), 1,
      anon_sym_GT,
    STATE(60), 1,
      aux_sym_type_name_repeat1,
  [984] = 2,
    ACTIONS(256), 1,
      sym_identifier,
    STATE(92), 1,
      sym_type_name,
  [991] = 2,
    ACTIONS(258), 1,
      anon_sym_SEMI,
    ACTIONS(260), 1,
      anon_sym_extending,
  [998] = 1,
    ACTIONS(226), 2,
      anon_sym_COLON_EQ,
      anon_sym_COLON_COLON,
  [1003] = 1,
    ACTIONS(213), 2,
      anon_sym_SEMI,
      anon_sym_do,
  [1008] = 1,
    ACTIONS(262), 2,
      anon_sym_SEMI,
      anon_sym_do,
  [1013] = 2,
    ACTIONS(264), 1,
      sym_identifier,
    STATE(106), 1,
      sym_qualified_identifier,
  [1020] = 2,
    ACTIONS(256), 1,
      sym_identifier,
    STATE(48), 1,
      sym_type_name,
  [1027] = 2,
    ACTIONS(266), 1,
      anon_sym_LBRACE,
    ACTIONS(268), 1,
      anon_sym_extending,
  [1034] = 1,
    ACTIONS(246), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [1039] = 2,
    ACTIONS(256), 1,
      sym_identifier,
    STATE(100), 1,
      sym_type_name,
  [1046] = 2,
    ACTIONS(256), 1,
      sym_identifier,
    STATE(40), 1,
      sym_type_name,
  [1053] = 2,
    ACTIONS(256), 1,
      sym_identifier,
    STATE(86), 1,
      sym_type_name,
  [1060] = 2,
    ACTIONS(256), 1,
      sym_identifier,
    STATE(102), 1,
      sym_type_name,
  [1067] = 1,
    ACTIONS(270), 1,
      sym_identifier,
  [1071] = 1,
    ACTIONS(272), 1,
      anon_sym_LPAREN,
  [1075] = 1,
    ACTIONS(201), 1,
      anon_sym_SEMI,
  [1079] = 1,
    ACTIONS(274), 1,
      anon_sym_COLON,
  [1083] = 1,
    ACTIONS(276), 1,
      anon_sym_SEMI,
  [1087] = 1,
    ACTIONS(278), 1,
      anon_sym_SEMI,
  [1091] = 1,
    ACTIONS(280), 1,
      sym_identifier,
  [1095] = 1,
    ACTIONS(282), 1,
      anon_sym_SEMI,
  [1099] = 1,
    ACTIONS(284), 1,
      anon_sym_LBRACE,
  [1103] = 1,
    ACTIONS(286), 1,
      anon_sym_each,
  [1107] = 1,
    ACTIONS(288), 1,
      anon_sym_LBRACE,
  [1111] = 1,
    ACTIONS(290), 1,
      sym_identifier,
  [1115] = 1,
    ACTIONS(292), 1,
      sym_identifier,
  [1119] = 1,
    ACTIONS(294), 1,
      sym_identifier,
  [1123] = 1,
    ACTIONS(296), 1,
      sym_identifier,
  [1127] = 1,
    ACTIONS(298), 1,
      anon_sym_SLASH,
  [1131] = 1,
    ACTIONS(300), 1,
      sym_identifier,
  [1135] = 1,
    ACTIONS(248), 1,
      anon_sym_SEMI,
  [1139] = 1,
    ACTIONS(302), 1,
      anon_sym_SEMI,
  [1143] = 1,
    ACTIONS(304), 1,
      anon_sym_COLON,
  [1147] = 1,
    ACTIONS(306), 1,
      anon_sym_SEMI,
  [1151] = 1,
    ACTIONS(308), 1,
      anon_sym_COLON_EQ,
  [1155] = 1,
    ACTIONS(310), 1,
      ts_builtin_sym_end,
  [1159] = 1,
    ACTIONS(312), 1,
      anon_sym_SEMI,
  [1163] = 1,
    ACTIONS(314), 1,
      anon_sym_COLON_EQ,
  [1167] = 1,
    ACTIONS(316), 1,
      anon_sym_type,
  [1171] = 1,
    ACTIONS(318), 1,
      anon_sym_SEMI,
  [1175] = 1,
    ACTIONS(320), 1,
      aux_sym_multi_line_comment_token1,
  [1179] = 1,
    ACTIONS(322), 1,
      anon_sym_SEMI,
  [1183] = 1,
    ACTIONS(324), 1,
      sym_identifier,
  [1187] = 1,
    ACTIONS(326), 1,
      sym_identifier,
  [1191] = 1,
    ACTIONS(328), 1,
      sym_identifier,
  [1195] = 1,
    ACTIONS(330), 1,
      aux_sym_comment_token1,
  [1199] = 1,
    ACTIONS(332), 1,
      sym_identifier,
  [1203] = 1,
    ACTIONS(334), 1,
      sym_identifier,
  [1207] = 1,
    ACTIONS(336), 1,
      aux_sym_comment_token1,
  [1211] = 1,
    ACTIONS(338), 1,
      anon_sym_SLASH,
  [1215] = 1,
    ACTIONS(340), 1,
      aux_sym_multi_line_comment_token1,
  [1219] = 1,
    ACTIONS(122), 1,
      anon_sym_SEMI,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 37,
  [SMALL_STATE(4)] = 73,
  [SMALL_STATE(5)] = 109,
  [SMALL_STATE(6)] = 145,
  [SMALL_STATE(7)] = 177,
  [SMALL_STATE(8)] = 209,
  [SMALL_STATE(9)] = 241,
  [SMALL_STATE(10)] = 273,
  [SMALL_STATE(11)] = 305,
  [SMALL_STATE(12)] = 334,
  [SMALL_STATE(13)] = 346,
  [SMALL_STATE(14)] = 358,
  [SMALL_STATE(15)] = 370,
  [SMALL_STATE(16)] = 382,
  [SMALL_STATE(17)] = 394,
  [SMALL_STATE(18)] = 406,
  [SMALL_STATE(19)] = 418,
  [SMALL_STATE(20)] = 430,
  [SMALL_STATE(21)] = 442,
  [SMALL_STATE(22)] = 454,
  [SMALL_STATE(23)] = 466,
  [SMALL_STATE(24)] = 478,
  [SMALL_STATE(25)] = 500,
  [SMALL_STATE(26)] = 512,
  [SMALL_STATE(27)] = 524,
  [SMALL_STATE(28)] = 536,
  [SMALL_STATE(29)] = 548,
  [SMALL_STATE(30)] = 564,
  [SMALL_STATE(31)] = 576,
  [SMALL_STATE(32)] = 588,
  [SMALL_STATE(33)] = 600,
  [SMALL_STATE(34)] = 612,
  [SMALL_STATE(35)] = 624,
  [SMALL_STATE(36)] = 636,
  [SMALL_STATE(37)] = 648,
  [SMALL_STATE(38)] = 660,
  [SMALL_STATE(39)] = 672,
  [SMALL_STATE(40)] = 683,
  [SMALL_STATE(41)] = 700,
  [SMALL_STATE(42)] = 713,
  [SMALL_STATE(43)] = 726,
  [SMALL_STATE(44)] = 734,
  [SMALL_STATE(45)] = 750,
  [SMALL_STATE(46)] = 758,
  [SMALL_STATE(47)] = 768,
  [SMALL_STATE(48)] = 784,
  [SMALL_STATE(49)] = 798,
  [SMALL_STATE(50)] = 806,
  [SMALL_STATE(51)] = 814,
  [SMALL_STATE(52)] = 823,
  [SMALL_STATE(53)] = 830,
  [SMALL_STATE(54)] = 837,
  [SMALL_STATE(55)] = 846,
  [SMALL_STATE(56)] = 857,
  [SMALL_STATE(57)] = 868,
  [SMALL_STATE(58)] = 878,
  [SMALL_STATE(59)] = 888,
  [SMALL_STATE(60)] = 898,
  [SMALL_STATE(61)] = 908,
  [SMALL_STATE(62)] = 918,
  [SMALL_STATE(63)] = 924,
  [SMALL_STATE(64)] = 934,
  [SMALL_STATE(65)] = 944,
  [SMALL_STATE(66)] = 954,
  [SMALL_STATE(67)] = 964,
  [SMALL_STATE(68)] = 974,
  [SMALL_STATE(69)] = 984,
  [SMALL_STATE(70)] = 991,
  [SMALL_STATE(71)] = 998,
  [SMALL_STATE(72)] = 1003,
  [SMALL_STATE(73)] = 1008,
  [SMALL_STATE(74)] = 1013,
  [SMALL_STATE(75)] = 1020,
  [SMALL_STATE(76)] = 1027,
  [SMALL_STATE(77)] = 1034,
  [SMALL_STATE(78)] = 1039,
  [SMALL_STATE(79)] = 1046,
  [SMALL_STATE(80)] = 1053,
  [SMALL_STATE(81)] = 1060,
  [SMALL_STATE(82)] = 1067,
  [SMALL_STATE(83)] = 1071,
  [SMALL_STATE(84)] = 1075,
  [SMALL_STATE(85)] = 1079,
  [SMALL_STATE(86)] = 1083,
  [SMALL_STATE(87)] = 1087,
  [SMALL_STATE(88)] = 1091,
  [SMALL_STATE(89)] = 1095,
  [SMALL_STATE(90)] = 1099,
  [SMALL_STATE(91)] = 1103,
  [SMALL_STATE(92)] = 1107,
  [SMALL_STATE(93)] = 1111,
  [SMALL_STATE(94)] = 1115,
  [SMALL_STATE(95)] = 1119,
  [SMALL_STATE(96)] = 1123,
  [SMALL_STATE(97)] = 1127,
  [SMALL_STATE(98)] = 1131,
  [SMALL_STATE(99)] = 1135,
  [SMALL_STATE(100)] = 1139,
  [SMALL_STATE(101)] = 1143,
  [SMALL_STATE(102)] = 1147,
  [SMALL_STATE(103)] = 1151,
  [SMALL_STATE(104)] = 1155,
  [SMALL_STATE(105)] = 1159,
  [SMALL_STATE(106)] = 1163,
  [SMALL_STATE(107)] = 1167,
  [SMALL_STATE(108)] = 1171,
  [SMALL_STATE(109)] = 1175,
  [SMALL_STATE(110)] = 1179,
  [SMALL_STATE(111)] = 1183,
  [SMALL_STATE(112)] = 1187,
  [SMALL_STATE(113)] = 1191,
  [SMALL_STATE(114)] = 1195,
  [SMALL_STATE(115)] = 1199,
  [SMALL_STATE(116)] = 1203,
  [SMALL_STATE(117)] = 1207,
  [SMALL_STATE(118)] = 1211,
  [SMALL_STATE(119)] = 1215,
  [SMALL_STATE(120)] = 1219,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(107),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(114),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(109),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(113),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_def_repeat1, 2, 0, 0),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_type_def_repeat1, 2, 0, 0), SHIFT_REPEAT(111),
  [71] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_type_def_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_type_def_repeat1, 2, 0, 0), SHIFT_REPEAT(113),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_type_def_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_def_repeat1, 2, 0, 0), SHIFT_REPEAT(117),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_def_repeat1, 2, 0, 0), SHIFT_REPEAT(119),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multi_line_comment, 3, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_def, 4, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_semicolon, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_def, 4, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_def, 4, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_def, 5, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_def, 6, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias_stmt, 5, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_def, 5, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_def, 6, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_def, 7, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotation, 5, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_annotation, 5, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trigger, 4, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_trigger, 4, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trigger, 3, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_trigger, 3, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 4, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 4, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_name, 1, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_name, 1, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_overloaded_field, 5, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_overloaded_field, 5, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multi_line_comment, 3, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trigger, 5, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_trigger, 5, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trigger, 7, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_trigger, 7, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 5, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 5, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trigger, 6, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_trigger, 6, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 7, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 7, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 6, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 6, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_name, 3, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_trigger_do_repeat1, 2, 0, 0),
  [192] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_trigger_do_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_name, 4, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_name, 5, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_name, 7, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_name, 6, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trigger_modifier, 2, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_attributes, 1, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_field_attributes_repeat1, 2, 0, 0),
  [223] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_field_attributes_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_qualified_identifier_repeat1, 2, 0, 0),
  [228] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_qualified_identifier_repeat1, 2, 0, 0), SHIFT_REPEAT(93),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualified_identifier, 2, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trigger_for_each, 2, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [243] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_name_repeat1, 2, 0, 0), SHIFT_REPEAT(116),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_name_repeat1, 2, 0, 0),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualified_identifier, 1, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trigger_when, 2, 0, 0),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [310] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trigger_do, 4, 0, 0),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gel(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "gel",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
